/**
 * The TokenType class
 */
public enum TokenType {
    ID_TOK, ADD_TOK, MUL_TOK, ASSIGN_TOK, CONST_TOK, FEATURE_TOK, IS_TOK, DO_TOK, PRINT_TOK, PARAN_TOK, END_TOK, GT_TOK, GE_TOK, LT_TOK, LE_TOK, IF_TOK, LOOP_TOK, DIV_TOK, SUB_TOK, EQ_TOK, NE_TOK, THEN_TOK, ELSE_TOK, FROM_TOK, UNTIL_TOK, EOS_TOK
}
